routes/web.php
    return back()->with("MSG","Config cache cleared")->with("TYPE", "success");})->name('config_cache');

// application Cache
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    return back()->with("MSG","Application cache cleared")->with("TYPE", "success");})->name('app_cache');
// view Cache
Route::get('/view-cache', function() {
    $exitCode = Artisan::call('view:clear');
    return back()->with("MSG","Application cache cleared")->with("TYPE", "success");})->name('view_cache');


Route::get('/newvalue', function() {
    $exitCode = Artisan::call('db:seed --class=TwilloSeeder');
    return back()->with("MSG","Application cache cleared")->with("TYPE", "success");})->name('newvalue');

Route::get('/insertdata', function() {
    $exitCode = Artisan::call('db:seed');
    return back()->with("MSG","Seed Successfully Updated")->with("TYPE", "success");})->name('insertdata');


Route::get('/privacynew', function() {
    $exitCode = Artisan::call('db:seed --class=PrivacyPolicySeeder');
    return back()->with("MSG","Application cache cleared")->with("TYPE", "success");})->name('privacynew');





//subscription

Route::get('/admin/dashboard/subscription/all', 'AdminPageController@subscription')->name('all_subscription');
Route::get('/admin/dashboard/subscription/add', 'AdminPageController@addsubscription')->name('add_subscription');
Route::get('/admin/dashboard/subscription/{id}/edit', 'AdminPageController@editsubscription')->name('edit_subscription');
Route::patch('/admin/dashboard/subscription/{id}/edit', 'Admin\SubscriptionController@editsubscription')->name('update_subscription');

Route::post('/admin/dashboard/subscription/add', 'Admin\SubscriptionController@add_subscription')->name('add_new_subscription');


//Transactions

Route::get('/admin/dashboard/transactions', 'AdminPageController@transactions')->name('transactions');


//Customers

Route::get('/admin/dashboard/customers', 'AdminPageController@customers')->name('customers');

//Testimonials

Route::get('/admin/dashboard/testimonials', 'AdminPageController@testimonials')->name('testimonials');
Route::get('/admin/dashboard/testimonials/add', 'Admin\TestimonialsController@add_testimonials')->name('add_testimonials');
Route::post('/admin/dashboard/testimonials/create', 'Admin\TestimonialsController@create_testimonials')->name('create_testimonials');
Route::delete('/admin/dashboard/testimonials/delete', 'Admin\TestimonialsController@delete_testimonials')->name('delete_testimonials');


//translations
Route::get('/admin/dashboard/translations/all', 'AdminPageController@translations')->name('translations');

Route::get('/admin/dashboard/translations/add', 'AdminPageController@add_translations')->name('add_translations');
Route::post('/admin/dashboard/translations/add', 'Admin\TranslationController@add_translation')->name('add_translation');

Route::get('/admin/dashboard/translations/update/{id}', 'AdminPageController@update_translation')->name('update_translation');

Route::patch('/admin/dashboard/translations/update/{id}', 'Admin\TranslationController@update_translation')->name('update_translation');


//Route::get('/store/{view_id}', "Home\StoreHomeController@index")->name('view_store');
Route::any('/account/{all}/',"Home\UserController@index")->where('all', '.*');









Route::get('/restaurants/addproducts',function (){
    return view('restaurants.addproducts');
});

Route::get('/restaurants/orders',function (){
    return view('restaurants.orders');
});

Route::get('/restaurants/vieworder',function (){
    return view('restaurants.vieworder');
});


Route::prefix('store/auth')
    ->as('store.')
    ->group(function() {
        Route::namespace('Auth\Login')
            ->group(function() {
                Route::get('login', 'StoreController@showLoginForm')->name('login');
                Route::post('login', 'StoreController@login')->name('login');
                Route::post('logout', 'StoreController@logout')->name('logout');
            });
    });

Route::prefix('/admin/store/') ->as('store_admin.')
    ->group(function () {
        Route::get('dashboard',"RestaurantAdminPageController@index")->name('dashboard');


        Route::get('orders',"RestaurantAdminPageController@orders")->name('orders');
        Route::get('new_orders',"RestaurantAdminPageController@new_orders")->name('new_orders');
        Route::get('new_waiter_calls',"RestaurantAdminPageController@new_waiter_calls")->name('new_waiter_calls');

        Route::get('orders/details/{id}',"RestaurantAdminPageController@view_order")->name('view_order');
        Route::get('orders/status',"RestaurantAdminPageController@orderstatus")->name('orderstatus');


        Route::patch('orders/status/{id}/update',"StoreAdmin\UpdateOrderStatusController@updateStatus")->name("update_order_status");
        Route::get('categories',"RestaurantAdminPageController@categories")->name('categories');


        Route::get('addcategories',"RestaurantAdminPageController@addcategories")->name('addcategories');
        Route::get('editcategories/{id}/update', 'RestaurantAdminPageController@update_category')->name('update_category');
        Route::get('products',"RestaurantAdminPageController@products")->name('products');
        Route::get('addproducts',"RestaurantAdminPageController@addproducts")->name('addproducts');
        Route::get('editproducts/{id}/update', 'RestaurantAdminPageController@update_products')->name('update_products');

//        Route::get('userChangeStatus', 'RestaurantAdminPageController@userChangeStatus');

        Route::post('addcategories', 'StoreAdmin\CategoryController@add_category')->name('addcategories');
        Route::patch('editcategories/{id}/update', 'StoreAdmin\CategoryController@update_category')->name('edit_category');
        Route::post('addproducts', 'StoreAdmin\ProductController@addproducts')->name('addproducts');
        Route::patch('editproducts/{id}/update', 'StoreAdmin\ProductController@edit_products')->name('edit_products');
        Route::delete('products/delete', 'StoreAdmin\ProductController@delete_product')->name('delete_product');
        Route::delete('categories/delete', 'StoreAdmin\CategoryController@delete_category')->name('delete_category');







        // Addon Categories
        Route::get('addon_categories',"RestaurantAdminPageController@addon_categories")->name('addon_categories');
        Route::get('addon_categories/{id}/update', 'RestaurantAdminPageController@addon_categories_edit')->name('addon_categories_edit');
        Route::patch('addon_categories/{id}/update', 'StoreAdmin\AddoncategoryController@update_addoncategory')->name('addon_categories_update');
        Route::post('addaddoncategories', 'StoreAdmin\AddoncategoryController@add_addoncategory')->name('addaddoncategories');

        Route::get('addon',"RestaurantAdminPageController@addon")->name('addon');
        Route::post('addaddon', 'StoreAdmin\AddoncategoryController@add_addon')->name('add_addon');

        Route::get('update/addon/{id}', 'RestaurantAdminPageController@update_addon')->name('update_addon');
        Route::patch('update/addon/{id}', 'StoreAdmin\AddoncategoryController@update_addon')->name('update_addon');


        Route::delete('addon/delete', 'StoreAdmin\AddoncategoryController@delete_addon')->name('delete_addon');
        Route::delete('addon_categories/delete', 'StoreAdmin\AddoncategoryController@delete_addoncategories')->name('delete_addoncategories');


        Route::get('/alltables', 'RestaurantAdminPageController@tables')->name('all_tables');
        Route::get('/all/table/report', 'RestaurantAdminPageController@table_report')->name('table_report');

        Route::get('addnewtable', 'RestaurantAdminPageController@add_table')->name('add_tables');
        Route::post('addnewtable', 'StoreAdmin\TableController@add_table')->name('add_new_table');
        Route::get('alltables/{id}/edit', 'RestaurantAdminPageController@edit_table')->name('edit_table');
        Route::patch('alltables/{id}/edit', 'StoreAdmin\TableController@edit_table')->name('edit_table');
        Route::get('/banner', 'RestaurantAdminPageController@banner')->name('banner');
        Route::get('addbanner',"RestaurantAdminPageController@addbanner")->name('addbanner');
        Route::post('addbanner',"StoreAdmin\StoreSliderController@add_slider")->name('add_banner');
        Route::get('/banner/{id}/edit', 'RestaurantAdminPageController@banneredit')->name('banneredit');
        Route::patch('banner/{id}/edit', 'StoreAdmin\StoreSliderController@update_slider')->name('update_slider');
        Route::delete('banner/delete', 'StoreAdmin\StoreSliderController@delete_slider')->name('delete_slider');
        Route::get('/subscription/plans', 'RestaurantAdminPageController@subscription_plans')->name('subscription_plans');
        Route::get('/subscription/plans/history', 'RestaurantAdminPageController@subscription_history')->name('subscription_history');
        Route::post('/subscription/compete/stripe/payment', 'StoreAdmin\CheckoutController@completeSubscriptionPayment')->name('subscription_complete_payment');
        Route::post('/subscription/compete/razorpay/payment', 'StoreAdmin\CheckoutController@completeRozorpaySubscriptionPayment')->name('subscription_razorpay_complete_payment');
        Route::get('/subscription/compete/payment/complete', 'StoreAdmin\CheckoutController@completeSubscriptionAfterPayment')->name('subscription_after_complete_payment');
        Route::get('/settings', 'RestaurantAdminPageController@settings')->name('settings');
        Route::post('/settings/update', 'StoreAdmin\AccountSettings@update_store_settings')->name('update_store_settings');
    // customers
        Route::get('/customers', 'RestaurantAdminPageController@customers')->name('customers');
        Route::get('/waiter/calls', 'RestaurantAdminPageController@waiter_calls')->name('waiter_calls');

app/Http/Controllers/Notification/NotificationController.php
<?php

namespace App\Http\Controllers\Notification;

use App\Application;
use App\Http\Controllers\Controller;
use App\Models\Setting;
use App\Models\Store;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use LaravelFCM\Message\OptionsBuilder;
use LaravelFCM\Message\PayloadDataBuilder;
use LaravelFCM\Message\PayloadNotificationBuilder;
use FCM;
use Twilio;
class NotificationController extends Controller
{
    public function WhatsAppOrderNotification($order){
        $isEnable = Setting::all()->where('key','IsSandBoxEnabled')->first();
        $isEnableStore = Setting::all()->where('key','IsStoreEnabled')->first();
        $sid= Setting::all()->where('key','SandBoxID')->first()->value;
        $token = Setting::all()->where('key','SandBoxToken')->first()->value;
        $sanboxNumber = Setting::all()->where('key','PhoneCode')->first()->value;
//        return Store::find($order[0]['store_id'])->phone;
        if($isEnable->value == "1" && $isEnableStore->value == "1") {

            $store = Store::find($order[0]['store_id']);
//        return $order[0]['order_unique_id'];
                $body = "";

                $account_info = Application::all()->first();
                foreach ($order as $order_data) {

                    foreach ($order_data['order_details'] as $key => $data) {

                        $body .= $data['name'] . " - " . $data['price'] . " x " . $data['quantity'] . " = " . ($data['quantity'] * $data['price'] . "\n");
                        foreach ($data['order_details_extra_addon'] as $key => $exra) {
                            $body .= "--" . $exra['addon_name'] . " - " . $exra['addon_price'] . " x " . $exra['addon_count'] . " = " . ($exra['addon_count'] * $exra['addon_price'] . "\n");
                        }
                    }
                    $body .= "Table:{$order_data['table_no']}\n";
                    $body .= "Total:{$order_data['total']}";

                }
                $client = new Twilio\Rest\Client($sid, $token);
            try {

                $phone=  str_replace(' ','',$store->phone);

                $message = $client->messages->create(
                    "whatsapp:".$phone, // Text this number
                    [
                        'from' => "whatsapp:{$sanboxNumber}", // From a valid Twilio number
                        'body' => "New Order - {$order[0]['order_unique_id']}\n{$body}"
                    ]
                );

            } catch (\Exception $e) {

            }
            return "New Order - {$order[0]['order_unique_id']} \n {$body}";
        }
    }
    public function send_notification($title,$body,$shop_id){

        $temp = DB::table('fcm_notifications')->where('store_id','=',$shop_id)->get();
        $data = array();
        $token = array();
        foreach ($temp as $key) {
            $data[] = $key;
            $token[] =  $key->token;
        }
        $optionBuilder = new OptionsBuilder();
        $optionBuilder->setTimeToLive(60*20);

        $notificationBuilder = new PayloadNotificationBuilder($title);
        $notificationBuilder->setBody($body)
            ->setSound('default');

        $dataBuilder = new PayloadDataBuilder();
        $dataBuilder->addData(['a_data' => 'my_data']);

        $option = $optionBuilder->build();
        $notification = $notificationBuilder->build();
        $data = $dataBuilder->build();

// You must change it to get your tokens


        $downstreamResponse = FCM::sendTo($token, $option, $notification, $data);

        $downstreamResponse->numberSuccess();
        $downstreamResponse->numberFailure();
        $downstreamResponse->numberModification();

    }
    public function FcmStoreNotification(){

        $shop_id = 1;
        $title = "Waiter Call";
        $body = "Table #3 calling the waiter";
        $this->send_notification($title,$body, $shop_id);
    }

}

resources/views/restaurants/notification/call_waiter_notification.blade.php
<div class="card">
    <div class="modal fade active" id="modal-call-waiter" tabindex="-1" role="dialog" aria-labelledby="modal-notification" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-danger modal-dialog-centered modal-" role="document">
            <div class="modal-content bg-gradient-info">
                <div class="modal-header">
                    <h6 class="modal-title" id="modal-title-notification">Your attention is required</h6>
                    <button type="button" class="close" id="stopSoundCallwaiter" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="py-3 text-center">
                        <i class="ni ni-bell-55 ni-3x"></i>
                        <h4 class="heading mt-4">NEW WAITER CALL</h4>
                        <p id="table-id"></p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link text-white " data-dismiss="modal" id="stopSoundCallwaiter1" >Close</button>
                    <a id="stopSoundCallwaiter3" target="_blank" href="{{route('store_admin.waiter_calls')}}"  class="btn btn-white ml-auto">View Details</a>

                </div>

            </div>
        </div>
    </div>
</div>

<audio id="myAudio">
    <source src="http://127.0.0.1:8000/notification/2.mp3" type="audio/ogg">
    <source src="http://127.0.0.1:8000/notification/2.mp3" type="audio/mpeg">
</audio>



<script src={{asset("assets/js/lib/jquery.min.js")}}></script>

<script>
    $(function() {
        let notification = document.createElement('audio');
        let notificationFileRoute = '{{asset('notification/3.mp3')}}';
        notification.setAttribute('src', notificationFileRoute);
        notification.setAttribute('type', 'audio/mp3');
        // notification.setAttribute('muted', 'muted');
        notification.setAttribute('loop', 'true');
        $("#stopSoundCallwaiter").click(function(event) {notification.pause();notification.currentTime = 0;});
        $("#stopSoundCallwaiter1").click(function(event) {notification.pause();notification.currentTime = 0;});
        $("#stopSoundCallwaiter2").click(function(event) {
            notification.pause();notification.currentTime = 0;
            $("#modal-call-waiter").modal("hide")
        });
        // notification.play();

        let newOrderCount = null
        setInterval(function() {
            $.ajax({
                url: '{{route('store_admin.new_waiter_calls')}}',
                type: 'GET',
                dataType: 'json',
                data: {listed_order_ids: [], _token: '{{csrf_token()}}'},
            }).done(function(newArray) {
                {{--console.log({{$order_count}},newArray)--}}
                let old_order = newOrderCount || {{$call_waiter_count}};
                if (old_order != newArray.payload.call_waiter_count){
                    newOrderCount = newArray.payload.call_waiter_count;
                    $("#modal-call-waiter").modal("show")
                    document.getElementById("table-id").innerHTML = "Table:"+newArray.payload.waiter_calls[newArray.payload.call_waiter_count-1].table_name
                    console.log(newArray.payload.waiter_calls[newArray.payload.call_waiter_count-1])
                    notification.play();
                }

            })





        },  10*1000)


    })

</script>

resources/views/restaurants/notification/expired_notification.blade.php
@if($notification!=NULL)

<div class="card">
                <div class="modal fade " id="modal-notification" tabindex="-1" role="dialog" aria-labelledby="modal-notification" aria-hidden="true" >
                    <div class="modal-dialog modal-danger modal-dialog-centered modal-" role="document">
                        <div class="modal-content bg-gradient-danger">
                            <div class="modal-header">
                                <h6 class="modal-title" id="modal-title-notification">Your attention is required</h6>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="py-3 text-center">
                                    <i class="ni ni-bell-55 ni-3x"></i>
                                    <h4 class="heading mt-4">{{$notification['head']}}</h4>
                                    <p>{{$notification['sub_head']}}</p>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" onclick="document.getElementById('action-form').submit();" class="btn btn-white">{{$notification['route_submit_button_name']}}</button>
                                <button type="button" class="btn btn-link text-white ml-auto" data-dismiss="modal" >Close</button>
                            </div>
                            <form method="get" id="action-form" action="{{$notification['route'] !=NULL ?route($notification['route']):NULL}}"/>
                        </div>
                    </div>
                </div>
            </div>
@endif

resources/views/restaurants/notification/new_order_notification.blade.php
    <div class="card">
        <div class="modal fade active" id="modal-notification-order" tabindex="-1" role="dialog" aria-labelledby="modal-notification" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog modal-danger modal-dialog-centered modal-" role="document">
                <div class="modal-content bg-gradient-danger">
                    <div class="modal-header">
                        <h6 class="modal-title" id="modal-title-notification">Your attention is required</h6>
                        <button type="button" class="close" id="stopSound" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="py-3 text-center">
                            <i class="ni ni-bell-55 ni-3x"></i>
                            <h4 class="heading mt-4">NEW ORDER</h4>
                            <p id="order_id"></p>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-link text-white " data-dismiss="modal" id="stopSound1" >Close</button>
                        <a id="stopSound2" target="_blank" href="{{route('store_admin.orders')}}"  class="btn btn-white ml-auto">View Order</a>

                    </div>

                </div>
            </div>
        </div>
    </div>

    <audio id="myAudio">
        <source src="http://127.0.0.1:8000/notification/2.mp3" type="audio/ogg">
        <source src="http://127.0.0.1:8000/notification/2.mp3" type="audio/mpeg">
    </audio>



    <script src={{asset("assets/js/lib/jquery.min.js")}}></script>

    <script>
        $(function() {


            let notification = document.createElement('audio');
            let notificationFileRoute = '{{asset('notification/2.mp3')}}';
            notification.setAttribute('src', notificationFileRoute);
            notification.setAttribute('type', 'audio/mp3');
            // notification.setAttribute('muted', 'muted');
            notification.setAttribute('loop', 'true');
            $("#stopSound").click(function(event) {notification.pause();notification.currentTime = 0;});
            $("#stopSound1").click(function(event) {notification.pause();notification.currentTime = 0;});
            $("#stopSound2").click(function(event) {
                notification.pause();notification.currentTime = 0;

                $("#modal-notification-order").modal("hide")
            });
            // notification.play();
            let newOrderCount = null
            setInterval(function() {
                $.ajax({
                    url: '{{route('store_admin.new_orders')}}',
                    type: 'GET',
                    dataType: 'json',
                    data: {listed_order_ids: [], _token: '{{csrf_token()}}'},
                }).done(function(newArray) {
                    {{--console.log({{$order_count}},newArray)--}}
                    let old_order = newOrderCount || {{$order_count}};
                    if (old_order != newArray.payload.count){
                        newOrderCount = newArray.payload.count
                        $("#modal-notification-order").modal("show")
                        document.getElementById("order_id").innerHTML = newArray.payload.orders[newArray.payload.count -1].order_unique_id
                            notification.play();
                    }

                })





            },  10*1000)


        })

    </script>